# Generated by Django 2.2.3 on 2019-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20190912_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
